export class Constants {
  static INITIAL_NUMBER_OF_BEERS_DISPLAYED = 12;
  static INITIAL_NUMBER_OF_PAGE = 1;
  static INITIAL_VALUE_BITERNESS_FILTER = 100;
  static INITIAL_VALUE_ALCOHOL_FILTER = 0;
  static HEIGHT_PERCENT_ALCOHOL_FILTER = 8;
  static DEBOUNCE_TIME_DURATION = 300;
  static MAX_IBU_INDICATOR = 100;
}
